repos:
  - repo: https://github.com/pre-commit/mirrors-black
    rev: v23.1.0  # Use the latest version
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-flake8
    rev: v4.0.1  # Use the latest version
    hooks:
      - id: flake8